export const GET_TEAM_REQUEST = "GET_TEAM_REQUEST";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_FAIL = "GET_TEAM_FAIL";
export const GET_SINGLE_TEAM_REQUEST = "GET_SINGLE_TEAM_REQUEST";
export const GET_SINGLE_TEAM_SUCCESS = "GET_SINGLE_TEAM_SUCCESS";
export const GET_SINGLE_TEAM_FAIL = "GET_SINGLE_TEAM_FAIL";
