const data = [
  {
    id: 1,
    Name: "Frederick",
    Email: "fred@yahoo.com",
    ProjectTile: "Wisdom Project",
    ContractType: "Spiritual",
    ProjectDeskOfficer: "Tunji",
    FrontDeskOfficer: "Emma Ejoor",
  },
  {
    id: 2,
    Name: "Susan",
    Email: "susanp@yahoo.com",
    ProjectTile: "Project33",
    ContractType: "Rec 1",
    ProjectDeskOfficer: "Fonsus Ali",
    FrontDeskOfficer: "Jude Akinwale",
  },
  {
    id: 3,
    Name: "Sammeky",
    Email: "sammeff@yahoo.com",
    ProjectTile: "Street Credit Card",
    ContractType: "4ku Collection",
    ProjectDeskOfficer: "Paulo Emeka",
    FrontDeskOfficer: "Ejoor Samson",
  },
  {
    id: 4,
    Name: "John Busco",
    Email: "buscoJ@yahoo.com",
    ProjectTile: "Deposit ID Project",
    ContractType: "Card ATM",
    ProjectDeskOfficer: "Sonia Ade",
    FrontDeskOfficer: "Emma Ejoor",
  },
  {
    id: 5,
    Name: "Fred Lookman",
    Email: "fredlook@yahoo.com",
    ProjectTile: "Project Zec",
    ContractType: "Seeker 1",
    ProjectDeskOfficer: "Carla",
    FrontDeskOfficer: "Emma",
  },
  {
    id: 6,
    Name: "Fran Kirby",
    Email: "franKi@yahoo.com",
    ProjectTile: "Project 22",
    ContractType: "Superhuman",
    ProjectDeskOfficer: "Osuji Ali",
    FrontDeskOfficer: "Fonsus Alphy",
  },
];

export default data;
