export const GET_HEAD_OF_PROCUREMENT_REQUEST = "GET_HEAD_OF_PROCUREMENT_REQUEST";
export const GET_HEAD_OF_PROCUREMENT_SUCCESS = "GET_HEAD_OF_PROCUREMENT_SUCCESS";
export const GET_HEAD_OF_PROCUREMENT_FAIL = "GET_HEAD_OF_PROCUREMENT_FAIL";
