export const GET_ALLPROJECTS_REQUEST = "GET_AllPROJECTS_REQUEST";
export const GET_ALLPROJECTS_SUCCESS = "GET_AllPROJECTS_SUCCESS";
export const GET_ALLPROJECTS_FAIL = "GET_AllPROJECTS_FAIL";

export const GET_NEWPROJECTS_REQUEST = "GET_NEWPROJECTS_REQUEST";
export const GET_NEWPROJECTS_SUCCESS = "GET_NEWPROJECTS_SUCCESS";
export const GET_NEWPROJECTS_FAIL = "GET_NEWPROJECTS_FAIL";

export const GET_PENDINGPROJECTS_REQUEST = "GET_PENDINGPROJECTS_REQUEST";
export const GET_PENDINGPROJECTS_SUCCESS = "GET_PENDINGPROJECTS_SUCCESS";
export const GET_PENDINGPROJECTS_FAIL = "GET_PENDINGPROJECTS_FAIL";

export const GET_CLOSEDPROJECTS_REQUEST = "GET_CLOSEDPROJECTS_REQUEST";
export const GET_CLOSEDPROJECTS_SUCCESS = "GET_CLOSEDPROJECTS_SUCCESS";
export const GET_CLOSEDPROJECTS_FAIL = "GET_CLOSEDPROJECTS_FAIL";

export const GET_APPROVEDPROJECTS_REQUEST = "GET_APPROVEDPROJECTS_REQUEST";
export const GET_APPROVEDPROJECTS_SUCCESS = "GET_APPROVEDPROJECTS_SUCCESS";
export const GET_APPROVEDPROJECTS_FAIL = "GET_APPROVEDPROJECTS_FAIL";

export const GET_TERMINATEDPROJECTS_REQUEST = "GET_TERMINATEDPROJECTS_REQUEST";
export const GET_TERMINATEDPROJECTS_SUCCESS = "GET_TERMINATEDPROJECTS_SUCCESS";
export const GET_TERMINATEDPROJECTS_FAIL = "GET_TERMINATEDPROJECTS_FAIL";
