export const GET_SINGLE_PROJECT_REQUEST = "GET_SINGLE_PROJECT_REQUEST";
export const GET_SINGLE_PROJECT_SUCCESS = "GET_SINGLE_PROJECT_SUCCESS";
export const GET_SINGLE_PROJECT_FAIL = "GET_SINGLE_PROJECT_FAIL";
export const GET_SINGLE_PROJECT_RESET = "GET_SINGLE_PROJECT_RESET";
