export const GET_PROCUREMENTHEAD_REQUEST = "GET_PROCUREMENTHEAD_REQUEST";
export const GET_PROCUREMENTHEAD_SUCCESS = "GET_PROCUREMENTHEAD_SUCCESS";
export const GET_PROCUREMENTHEAD_FAIL = "GET_PROCUREMENTHEAD_FAIL";

export const GET_FRONTDESK_REQUEST = "GET_FRONTDESK_REQUEST";
export const GET_FRONTDESK_SUCCESS = "GET_FRONTDESK_SUCCESS";
export const GET_FRONTDESK_FAIL = "GET_FRONTDESK_FAIL";

export const GET_PROJECTDESK_REQUEST = "GET_PROJECTDESK_REQUEST";
export const GET_PROJECTDESK_SUCCESS = "GET_PROJECTDESK_SUCCESS";
export const GET_PROJECTDESK_FAIL = "GET_PROJECTDESK_FAIL";
