export const CREATE_NEWPROJECTLIST_REQUEST = "CREATE_NEWPROJECTLIST_REQUEST";
export const CREATE_NEWPROJECTLIST_SUCCESS = "CREATE_NEWPROJECTLIST_SUCCESS";
export const CREATE_NEWPROJECTLIST_FAIL = "CREATE_NEWPROJECTLIST_FAIL";
export const CREATE_NEWPROJECTLIST_RESET = "CREATE_NEWPROJECTLIST_RESET";
