export const INITIATE_PROJECT_REQUEST = "INITIATE_PROJECT_REQUEST";
export const INITIATE_PROJECT_SUCCESS = "INITIATE_PROJECT_SUCCESS";
export const INITIATE_PROJECT_FAIL = "INITIATE_PROJECT_FAIL";
export const INITIATE_PROJECT_RESET = "INITIATE_PROJECT_RESET";

export const GET_CONFIRMED_PROJECT_REQUEST = "GET_CONFIRMED_PROJECT_REQUEST";
export const GET_CONFIRMED_PROJECT_SUCCESS = "GET_CONFIRMED_PROJECT_SUCCESS";
export const GET_CONFIRMED_PROJECT_FAIL = "GET_CONFIRMED_PROJECT_FAIL";

export const GET_PENDING_PROJECT_REQUEST = "GET_PENDING_PROJECT_REQUEST";
export const GET_PENDING_PROJECT_SUCCESS = "GET_PENDING_PROJECT_SUCCESS";
export const GET_PENDING_PROJECT_FAIL = "GET_PENDING_PROJECT_FAIL";

export const GET_REJECTED_PROJECT_REQUEST = "GET_REJECTED_PROJECT_REQUEST";
export const GET_REJECTED_PROJECT_SUCCESS = "GET_REJECTED_PROJECT_SUCCESS";
export const GET_REJECTED_PROJECT_FAIL = "GET_REJECTED_PROJECT_FAIL";


