export const CREATE_ROLES_REQUEST = "CREATE_ROLES_REQUEST";
export const CREATE_ROLES_SUCCESS = "CREATE_ROLES_SUCCESS";
export const CREATE_ROLES_FAIL = "CREATE_ROLES_FAIL";
export const CREATE_ROLES_RESET = "CREATE_ROLES_RESET";

export const GET_ROLES_REQUEST = "GET_ROLES_REQUEST";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAIL = "GET_ROLES_FAIL";
export const GET_ROLES_RESET = "GET_ROLES_RESET";

export const UPDATE_ROLES_REQUEST = "UPDATE_ROLES_REQUEST";
export const UPDATE_ROLES_SUCCESS = "UPDATE_ROLES_SUCCESS";
export const UPDATE_ROLES_FAIL = "UPDATE_ROLES_FAIL";
export const UPDATE_ROLES_RESET = "UPDATE_ROLES_RESET";

export const DELETE_ROLES_REQUEST = "DELETE_ROLES_REQUEST";
export const DELETE_ROLES_SUCCESS = "DELETE_ROLES_SUCCESS";
export const DELETE_ROLES_FAIL = "DELETE_ROLES_FAIL";
export const DELETE_ROLES_RESET = "DELETE_ROLES_RESET";
