export const CREATE_SUBUNIT_REQUEST = "CREATE_SUBUNIT_REQUEST";
export const CREATE_SUBUNIT_SUCCESS = "CREATE_SUBUNIT_SUCCESS";
export const CREATE_SUBUNIT_FAIL = "CREATE_SUBUNIT_FAIL";
export const CREATE_SUBUNIT_RESET = "CREATE_SUBUNIT_RESET";

export const GET_SUBUNIT_REQUEST = "GET_SUBUNIT_REQUEST";
export const GET_SUBUNIT_SUCCESS = "GET_SUBUNIT_SUCCESS";
export const GET_SUBUNIT_FAIL = "GET_SUBUNIT_FAIL";
export const GET_SUBUNIT_RESET = "GET_SUBUNIT_RESET";

export const UPDATE_SUBUNIT_REQUEST = "UPDATE_SUBUNIT_REQUEST";
export const UPDATE_SUBUNIT_SUCCESS = "UPDATE_SUBUNIT_SUCCESS";
export const UPDATE_SUBUNIT_FAIL = "UPDATE_SUBUNIT_FAIL";
export const UPDATE_SUBUNIT_RESET = "UPDATE_SUBUNIT_RESET";

export const DELETE_SUBUNIT_REQUEST = "DELETE_SUBUNIT_REQUEST";
export const DELETE_SUBUNIT_SUCCESS = "DELETE_SUBUNIT_SUCCESS";
export const DELETE_SUBUNIT_FAIL = "DELETE_SUBUNIT_FAIL";
export const DELETE_SUBUNIT_RESET = "DELETE_SUBUNIT_RESET";
